### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by zhuqingquan5510** [sklasfeld/DANPOS3#1] opened 2022-01-12 14:45 UTC
hello,
cmd:  python ~/software/DANPOS3/danpos.py dpos S8_MN_merge.bam:S24_MN_merge.bam -m 1  -t 1e-5 
I have just ran into an error using DANPOS3:
### The end of the log file ###
97000 simulated...
98000 simulated...
99000 simulated...
99931 simulated.
analyzing...
combining nucleosome and differential positions...
calculating differential values for positions...
chr1

Traceback (most recent call last):
  File "DANPOS3/danpos.py", line 1365, in <module>

    if sys.argv[1]=='dpos':runDANPOS(command='dpos')
  File "DANPOS3/danpos.py", line 424, in runDANPOS
    pcfer=0)#args.pcfer)#0)                  
  File "/D_test/DANPOS3/functions.py", line 511, in danpos
    dis=distance,rd=rd,test=test,fdrsimu=0,fdrRegions=peaks,occFDRlist=occFDRlist,fuzFDRlist=fuzFDRlist,fdr=fdr)
  File "/D_test/DANPOS3/functions.py", line 1172, in allPositionsInOneFile
    temp=log10fuztest(pc=p1,pt=p2,cr=cr,cwig=cwig,twig=twig,rd=rd)
  File "/D_test/DANPOS3/functions.py", line 1341, in log10fuztest
    if vc<vt:p=pf(unnumpy(div(vc,vt)),unnumpy(cc),unnumpy(ct), log_bool=True)
  File "/D_test/DANPOS3/functions.py", line 66, in pf

    answer = log(answer)
ValueError: math domain error

**Comment by SimHolz** [comment] 2022-02-09 20:14
The problem is due to a error where the program tries to calculate log(0). The 0 occurs due to a floating point error in value calculation (=number smaller than python can handle, therefore it uses 0 instead. Happens below 2.2250738585072014e-308). 

I will write a more comprehensive fix, but until then try to edit the following in `functions.py`: 

```python
# equivalent of pf function in R
# q - vector of quantiles
# df1, df2 - degrees of freedom
# lower_tail - logical; if TRUE probabilities are 
#   P[x<=x], otherwise P[X>x]
# log_bool - if true probabilities p are given as log(p)
def pf(q,df1, df2, lower_tail=True, log_bool=False):
    answer = f.cdf(q, dfn=df1,dfd=df2)
    if not lower_tail:
        answer=1-answer
    if log_bool:
        answer = log(answer)
    return(answer)
```

to

```python
# equivalent of pf function in R
# q - vector of quantiles
# df1, df2 - degrees of freedom
# lower_tail - logical; if TRUE probabilities are 
#   P[x<=x], otherwise P[X>x]
# log_bool - if true probabilities p are given as log(p)
def pf(q,df1, df2):
    answer = f.logcdf(q, dfn=df1,dfd=df2)/log(10) #divide by log(10) to get log10Pval
      return(answer)
```

**Comment by zhuqingquan5510** [comment] 2022-02-28 08:10
hello,
I edit functions.py , but  I got a new error,what should I do NEXT ?

B73V4_ctg22 : 81 summits, merging ...
197.0
496.0
19 left
B73V4_ctg228 : 61 summits, merging ...
612.0
619.0
11 left
B73V4_ctg126 : 4 summits, merging ...
2 left
calculating positioning score
1
pf test parameters
0.3647288875355743
1901.3010494739694
20
Traceback (most recent call last):
  File "/gss1/home/zqq20190923/github/DANPOS3/danpos.py", line 1365, in <module>
    if sys.argv[1]=='dpos':runDANPOS(command='dpos')
  File "/gss1/home/zqq20190923/github/DANPOS3/danpos.py", line 424, in runDANPOS
    pcfer=0)#args.pcfer)#0)
  File "/gss1/home/zqq20190923/github/DANPOS3/functions.py", line 441, in danpos
    smtgroups[groupname]=pooledgroups[groupname].callPositions(os.path.join(opath,'pooled',groupname+addname+"positions.xls"),width=width,distance=distance,edge=0,fill_gap=fill_gap,fill_value=fill_value,pcut=pheight,height=height,calculate_P_value=0,poscal=1,regions=peaks,rd=rd)
  File "/gss1/home/zqq20190923/github/DANPOS3/wig.py", line 395, in callPositions
    smts.positioning(twig,rd=rd)
  File "/gss1/home/zqq20190923/github/DANPOS3/summits.py", line 82, in positioning
    temp=log10fuztest(pc=ps[i],pt=ps[i],cr=cr,cwig=wig,twig=None,rd=rd)
  File "/gss1/home/zqq20190923/github/DANPOS3/functions.py", line 1338, in log10fuztest
    unnumpy(c),unnumpy(bc), log_bool=True)
TypeError: pf() got an unexpected keyword argument 'log_bool'


thanks a lot

**Comment by SimHolz** [comment] 2022-03-03 09:52
Ah sorry, this is my bad... 
The script still tries to use the arguments  `log_bool` and `lower_tail` although my new function doesn't use them anymore.
You can either change all occurrences of the `pf()` function in DANPOS (which is done in the pull request #3 ) or you include and just ignore the arguments.   

This code should work:

```python
# equivalent of pf function in R
# q - vector of quantiles
# df1, df2 - degrees of freedom
# lower_tail - logical; if TRUE probabilities are 
#   P[x<=x], otherwise P[X>x]
# log_bool - if true probabilities p are given as log(p)
def pf(q,df1, df2, lower_tail=True, log_bool=False):
    # lower_tail and log_bool are included for legacy reasons but ignored.
    _ = lower_tail
    _ = log_bool 

    answer = f.logcdf(q, dfn=df1,dfd=df2)/log(10) #divide by log(10) to get log10Pval
      return(answer)
```

please let me know if you run into additional issues!

**Comment by zhuqingquan5510** [comment] 2022-03-04 01:35
Thank you. After modifying the above code, the job have ended successfully. However, a warning appeared at the end of the log file.  I don't know if this will have any effect on the result. 

**calculating fuzziness differential FDR...
time elapsed: 15102.831856966019 seconds

total time elapsed: 4 hours 11 minutes 42 seconds

job done, cheers!

/gss1/home/zqq20190923/miniconda3/envs/python3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:891: RuntimeWarning: divide by zero encountered in log
  return log(self._cdf(x, *args))**

Also, I would like to ask you which columns of the DANPOS results should be used to determine each of the three types of dynamic nucleosomes, as I have seen different identification methods in two articles：
1）article 1 -- Nucleosome landscape reflects phenotypic differences in Trypanosoma cruzi life forms   
_position shift   --- point_diff_FDR < 0.05
occupancy change --- smt_diff_FDR < 0.05
fuzziness change  ---  fuzziness_diff_FDR <0.05_

2）article 2 -- Arabidopsis Chromatin Assembly Factor 1 is required for occupancy and position of a subset of nucleosomes
_position shift   --- treat2control_dis [50,90]
occupancy change --- smt_diff_FDR <0.05
fuzziness change  ---  fuzziness_diff_FDR <0.05_ 

best wishes.

**Comment by zhuqingquan5510** [comment] 2022-03-04 01:36
Thank you. After modifying the above code, the job have ended successfully. However, a warning appeared at the end of the log file. I don't know if this will have any effect on the result.

_calculating fuzziness differential FDR...
time elapsed: 15102.831856966019 seconds

total time elapsed: 4 hours 11 minutes 42 seconds

job done, cheers!

/gss1/home/zqq20190923/miniconda3/envs/python3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:891: RuntimeWarning: divide by zero encountered in log
return log(self._cdf(x, args))_

Also, I would like to ask you which columns of the DANPOS results should be used to determine each of the three types of dynamic nucleosomes, as I have seen different identification methods in two articles：
1）article 1 -- Nucleosome landscape reflects phenotypic differences in Trypanosoma cruzi life forms
position shift --- point_diff_FDR < 0.05
occupancy change --- smt_diff_FDR < 0.05
fuzziness change --- fuzziness_diff_FDR <0.05

2）article 2 -- Arabidopsis Chromatin Assembly Factor 1 is required for occupancy and position of a subset of nucleosomes
position shift --- treat2control_dis [50,90]
occupancy change --- smt_diff_FDR <0.05
fuzziness change --- fuzziness_diff_FDR <0.05

best wishes.

**Comment by SimHolz** [comment] 2022-03-04 11:04
>  /gss1/home/zqq20190923/miniconda3/envs/python3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:891: RuntimeWarning: divide by zero encountered in log
return log(self.cdf(x, args))

this warning is more or less the same warning that initially stopped the program from running. As I explained before this is in my opinion due to really low pvalues and the way python can handle them. This results in a log(0) situation. 
In the original problem this resulted in a math domain error and the program crashed. I changed the code a bit so now the package SciPy deals with the same calculation and returns `-inf` as log10 pvalue and the warning above.

> Also, I would like to ask you which columns of the DANPOS results should be used to determine each of the three types of dynamic nucleosomes, as I have seen different identification methods in two articles：
1）article 1 -- Nucleosome landscape reflects phenotypic differences in Trypanosoma cruzi life forms
position shift --- point_diff_FDR < 0.05
occupancy change --- smt_diff_FDR < 0.05
fuzziness change --- fuzziness_diff_FDR <0.05
> 2）article 2 -- Arabidopsis Chromatin Assembly Factor 1 is required for occupancy and position of a subset of nucleosomes
position shift --- treat2control_dis [50,90]
occupancy change --- smt_diff_FDR <0.05
fuzziness change --- fuzziness_diff_FDR <0.05

This is a completely different topic. The DANPOS authors suggest using point_diff to determine dynamic nucleosomes and treat2control_dis, smt_diff and fuzziness_diff to further categorise the nucleosomes (See Frequently asked questions in the  attached documentation of the old DANPOS 1.0.1). In DANPOS1 there was no FDR so they used the log10 values with a threshold. In DANPOS2 they included a calculation of some kind of FDRs and use those for determination of dynamic nucleosomes. 

so best to my knowledge the recommendations from Chen et al are: 
position shift --- point_diff_FDR < 0.05 + treat2control_dis [50,90]
occupancy change --- point_diff_FDR < 0.05 + smt_diff_FDR <0.05
fuzziness change --- point_diff_FDR < 0.05 + fuzziness_diff_FDR <0.05

I myself don't like the FDR calculation of DANPOS2 and still use log10 pvalues and additionally I chose to ignore the point_diff completely. In case of not using DANPOS FDR you have to be careful to choose a log10 pvalue that suits your data as the pvalues of the statistical test used in DANPOS depends on the read coverage and can be greatly modified by the `--count` parameter for example. And be aware that a suitable threshold might be different between smt_diff and fuzziness_diff! (for example fuzziness < -50, smt_diff < -10). 

So I use:
position shift --- treat2control_dis [MY THRESHOLDS]
occupancy change --- smt_diff_log10pval < MY THRESHOLD
fuzziness change --- fuzziness_diff_log10pval < MY THRESHOLD

[Documentation.pdf](https://github.com/sklasfeld/DANPOS3/files/8185127/Documentation.pdf)

**Comment by zhuqingquan5510** [comment] 2022-03-04 12:15
AH, I got it. 
Thank you for your patience.

**Comment by SimHolz** [comment] 2022-03-04 12:23
You're Welcome! 

I guess @sklasfeld could close this issue now.

**Closed** 2022-03-04 12:55 UTC
